In [1]:
from causalinference import CausalModel
from causalinference.utils import random_data
Y, D, X = random_data()
causal = CausalModel(Y, D, X)

In [2]:
print(causal.summary_stats)


Summary Statistics

                      Controls (N_c=2474)        Treated (N_t=2526)             
       Variable         Mean         S.d.         Mean         S.d.     Raw-diff
--------------------------------------------------------------------------------
              Y       -0.979        1.731        4.999        3.038        5.979

                      Controls (N_c=2474)        Treated (N_t=2526)             
       Variable         Mean         S.d.         Mean         S.d.     Nor-diff
--------------------------------------------------------------------------------
             X0       -0.298        0.942        0.309        0.946        0.643
             X1       -0.331        0.952        0.365        0.945        0.734
             X2       -0.325        0.953        0.321        0.940        0.683



In [3]:
print Y

[ 1.20050092 -1.6234815  -4.1039495  ...,  3.69938636  6.97564572
  5.53833445]


In [4]:
print len(Y)

5000


In [8]:
print Y[1]

-1.62348150294


In [6]:
print len(D)

5000


In [7]:
print D

[0 0 0 ..., 1 1 1]


In [9]:
print type(D)

<type 'numpy.ndarray'>


In [10]:
print X

[[ 0.11397722 -1.50632986  1.82324589]
 [ 0.33427711 -1.37102103 -0.54178945]
 [-1.6984341  -1.45582941 -0.16334798]
 ..., 
 [ 0.18455614  0.49899026 -0.61167924]
 [ 0.44975097 -0.74715083  2.16987318]
 [-1.05599124  1.79133336  0.42363047]]


In [11]:
print type(X)

<type 'numpy.ndarray'>


In [12]:
causal.est_via_matching()
print(causal.estimates)


Treatment Effect Estimates: Matching

                     Est.       S.e.          z      P>|z|      [95% Conf. int.]
--------------------------------------------------------------------------------
           ATE      3.272      0.089     36.843      0.000      3.098      3.446
           ATC      2.328      0.119     19.489      0.000      2.094      2.562
           ATT      4.196      0.103     40.797      0.000      3.994      4.398

